import time
import json
import os
import re
import requests
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from mail_service import get_gmail_service, get_unread_emails, mark_as_read, send_reply, get_thread_messages
from llm import classify_email

load_dotenv()

CALENDAR_SERVICE_URL = "http://localhost:8002"
PROCESSED_IDS_FILE = "processed_ids.json"
AI_DISCLAIMER = "\n\n---\n⚠️ This reply was generated by an AI email assistant (Mail Pilot). If you believe this was sent in error, please reply to this thread."
IST = ZoneInfo("Asia/Kolkata")


def load_processed_ids():
    if os.path.exists(PROCESSED_IDS_FILE):
        with open(PROCESSED_IDS_FILE, "r") as f:
            return set(json.load(f))
    return set()


def save_processed_id(email_id):
    ids = load_processed_ids()
    ids.add(email_id)
    with open(PROCESSED_IDS_FILE, "w") as f:
        json.dump(list(ids), f)


def log_activity(action: str, detail: str = "", status: str = "success"):
    try:
        requests.post(
            f"{CALENDAR_SERVICE_URL}/log",
            json={
                "action": action,
                "detail": detail,
                "status": status,
                "timestamp": datetime.now().strftime("%d %b %Y, %I:%M %p")
            },
            timeout=5
        )
    except Exception as e:
        print(f"[LOG ERROR] {e}")


# ─────────────────────────────────────────────
# TIMEZONE HELPERS
# ─────────────────────────────────────────────

def get_timezone_for_email(email: str) -> str:
    domain_tz = {
        "gmail.com": "Asia/Kolkata",
        "yahoo.com": "America/New_York",
        "outlook.com": "Europe/London",
        "hotmail.com": "Europe/London",
    }
    domain = email.split("@")[-1].lower()
    return domain_tz.get(domain, "Asia/Kolkata")


def format_time_for_attendees(slot: dict, attendees: list) -> str:
    lines = []
    seen_tz = set()
    for email in attendees:
        tz_str = get_timezone_for_email(email)
        if tz_str in seen_tz:
            continue
        seen_tz.add(tz_str)
        tz = ZoneInfo(tz_str)
        local_dt = datetime.fromisoformat(slot["start"]).astimezone(tz)
        lines.append(
            f"  • {email}: {local_dt.strftime('%I:%M %p')} ({tz_str.split('/')[-1].replace('_', ' ')})"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────
# TIME EXTRACTION VIA GROQ
# ─────────────────────────────────────────────

def extract_slots_from_text(text: str) -> dict:
    now = datetime.now(tz=IST)
    now_str = now.strftime("%Y-%m-%d %H:%M %Z")

    try:
        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {os.getenv('GROQ_API_KEY')}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            f"Current time is {now_str}. "
                            "Extract the meeting time from the email text. "
                            "Reply with ONLY a JSON object like this: "
                            "{\"start\": \"2026-04-05T16:00:00+05:30\", \"end\": \"2026-04-05T17:00:00+05:30\"}. "
                            "Use IST timezone (+05:30). Duration is 1 hour unless specified. "
                            "If no specific time mentioned, use tomorrow at 10am IST. "
                            "Do not include any explanation, only the JSON."
                        )
                    },
                    {
                        "role": "user",
                        "content": text
                    }
                ],
                "temperature": 0
            },
            timeout=10
        ).json()

        content = resp["choices"][0]["message"]["content"].strip()
        content = content.replace("```json", "").replace("```", "").strip()
        times = json.loads(content)
        print(f"[TIME EXTRACT] start={times['start']} end={times['end']}")
        return {
            "time_min": times["start"],
            "time_max": times["end"]
        }

    except Exception as e:
        print(f"[TIME EXTRACT ERROR] {e}")
        fallback = now.replace(hour=10, minute=0, second=0, microsecond=0) + timedelta(days=1)
        return {
            "time_min": fallback.isoformat(),
            "time_max": (fallback + timedelta(hours=8)).isoformat()
        }


# ─────────────────────────────────────────────
# ATTENDEE EXTRACTION
# ─────────────────────────────────────────────

def extract_attendees(email: dict) -> list:
    attendees = set()
    sender = email.get("sender", "")
    if "@" in sender:
        match = re.search(r'<(.+?)>', sender)
        attendees.add(match.group(1) if match else sender.strip())
    found = re.findall(r'[\w.+-]+@[\w-]+\.[a-zA-Z]{2,}', email.get("body", ""))
    attendees.update(found)
    return list(attendees)


# ─────────────────────────────────────────────
# CALENDAR CALLS
# ─────────────────────────────────────────────

def find_slots(attendees, time_min, time_max, duration=60):
    try:
        resp = requests.post(
            f"{CALENDAR_SERVICE_URL}/calendar/find-slots",
            json={
                "attendee_emails": attendees,
                "time_min": time_min,
                "time_max": time_max,
                "duration_minutes": duration,
                "max_slots": 3,
            },
            timeout=10
        )
        resp.raise_for_status()
        return resp.json().get("available_slots", [])
    except Exception as e:
        print(f"[ERROR] find-slots failed: {e}")
        log_activity("find-slots failed", str(e), "error")
        return []


def create_event(summary, slot, attendees, description=""):
    try:
        resp = requests.post(
            f"{CALENDAR_SERVICE_URL}/calendar/create-event",
            json={
                "summary": summary,
                "start_dt": slot["start"],
                "end_dt": slot["end"],
                "attendee_emails": attendees,
                "description": description,
                "timezone_str": "Asia/Kolkata",
                "send_updates": "all",
            },
            timeout=10
        )
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        print(f"[ERROR] create-event failed: {e}")
        log_activity("create-event failed", str(e), "error")
        return None


# ─────────────────────────────────────────────
# REPLY BUILDERS
# ─────────────────────────────────────────────

def build_schedule_reply(slots, event_result, attendees):
    if event_result and event_result.get("status") == "created":
        ist = ZoneInfo("Asia/Kolkata")
        start_dt = datetime.fromisoformat(slots[0]["start"]).astimezone(ist)
        end_dt = start_dt + timedelta(hours=1)
        date_str = start_dt.strftime("%A, %d %B %Y")
        start_str = start_dt.strftime("%I:%M %p")
        end_str = end_dt.strftime("%I:%M %p")
        attendee_list = "\n".join([f"  • {a}" for a in attendees])
        tz_lines = format_time_for_attendees(slots[0], attendees)
        return (
            f"Hi,\n\n"
            f"Your meeting has been successfully scheduled!\n\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"  MEETING CONFIRMATION\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"  Date     : {date_str}\n"
            f"  Time     : {start_str} – {end_str} IST\n"
            f"  Duration : 1 hour\n"
            f"  Attendees:\n{attendee_list}\n\n"
            f"  Local times:\n{tz_lines}\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            f"A Google Calendar invite has been sent to all attendees.\n\n"
            f"Thanks,\nMail Pilot Assistant"
            + AI_DISCLAIMER
        )
    elif event_result and event_result.get("status") == "duplicate":
        existing_start = event_result.get("start", "")
        if existing_start:
            ist = ZoneInfo("Asia/Kolkata")
            existing_dt = datetime.fromisoformat(existing_start).astimezone(ist)
            existing_str = existing_dt.strftime("%A, %d %B %Y at %I:%M %p IST")
            return (
                f"Hi,\n\nYou already have a meeting scheduled at {existing_str}.\n\n"
                "This time slot is taken! Could you please suggest a different time "
                "and I'll schedule it for you?\n\nThanks!"
                + AI_DISCLAIMER
            )
        return (
            "Hi,\n\nThis time slot is already booked! "
            "Could you please suggest a different time?\n\nThanks!"
            + AI_DISCLAIMER
        )
    elif slots:
        ist = ZoneInfo("Asia/Kolkata")
        slot_options = "\n".join([
            f"• {datetime.fromisoformat(s['start']).astimezone(ist).strftime('%A, %d %B %Y at %I:%M %p IST')}"
            for s in slots
        ])
        return (
            f"Hi,\n\nI found these available time slots:\n\n{slot_options}\n\n"
            "Please reply with your preferred slot and I'll confirm the meeting."
            + AI_DISCLAIMER
        )
    else:
        return (
            "Hi,\n\nI wasn't able to find a common available slot in the requested window. "
            "Could you suggest a few alternative times?\n\nThanks!"
            + AI_DISCLAIMER
        )


def build_update_reply(thread_messages):
    recent = thread_messages[-3:] if len(thread_messages) > 3 else thread_messages
    summary_lines = [
        f"• {msg.get('sender', 'Unknown')}: {msg.get('snippet', '')[:200]}"
        for msg in recent
    ]
    return (
        "Hi,\n\nHere's a quick summary of this thread:\n\n"
        + "\n".join(summary_lines)
        + "\n\nLet me know if you need more details!"
        + AI_DISCLAIMER
    )


# ─────────────────────────────────────────────
# EMAIL HANDLERS
# ─────────────────────────────────────────────

def handle_schedule(service, email):
    print(f"[SCHEDULE] {email['subject']}")
    print(f"[SCHEDULE] BODY: {email['body'][:200]}")
    attendees = extract_attendees(email)
    print(f"[SCHEDULE] Attendees: {attendees}")

    # Check if time is clear enough to proceed
    try:
        clarity_resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {os.getenv('GROQ_API_KEY')}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are an assistant that checks if a scheduling email contains enough information to book a meeting. "
                            "Reply with ONLY a JSON object like this: "
                            "{\"clear\": true} if the email contains a specific date and time, OR "
                            "{\"clear\": false, \"question\": \"<a single follow-up question to ask the sender>\"} if the time is vague or missing. "
                            "Examples of unclear: 'sometime next week', 'in the morning', 'soon', 'at your convenience', no time mentioned at all. "
                            "Examples of clear: 'tomorrow at 3pm', 'Monday April 7th at 10am', 'this Friday at 2:30pm IST'. "
                            "Only reply with the JSON, nothing else."
                        )
                    },
                    {
                        "role": "user",
                        "content": email["body"][:500]
                    }
                ],
                "temperature": 0,
                "max_tokens": 100
            },
            timeout=10
        ).json()

        clarity_content = clarity_resp["choices"][0]["message"]["content"].strip()
        clarity_content = clarity_content.replace("```json", "").replace("```", "").strip()
        match = re.search(r'\{.*\}', clarity_content, re.DOTALL)
        clarity = json.loads(match.group()) if match else {"clear": True}

    except Exception as e:
        print(f"[SCHEDULE] Clarity check failed: {e}")
        clarity = {"clear": True}

    # If time is unclear, ask follow-up and stop
    if not clarity.get("clear", True):
        question = clarity.get("question", "Could you please provide a specific date and time for the meeting?")
        reply = (
            f"Hi,\n\n"
            f"Thanks for reaching out! I'd love to help schedule this meeting.\n\n"
            f"{question}\n\n"
            f"Once you confirm, I'll get it booked right away.\n\n"
            f"Thanks,\nMail Pilot Assistant"
            + AI_DISCLAIMER
        )
        send_reply(service, email, reply)
        log_activity("Follow-up sent", f"Unclear time in: {email['subject']}", "info")
        print("[SCHEDULE] Time unclear — follow-up question sent")
        save_processed_id(email["id"])
        mark_as_read(service, email["id"])
        return

    # Time is clear — proceed with normal scheduling
    slots_params = extract_slots_from_text(email["body"])
    slots = find_slots(attendees, slots_params["time_min"], slots_params["time_max"])
    print(f"[SCHEDULE] Found {len(slots)} slots")

    event_result = None
    if slots:
        event_result = create_event(
            summary=email.get("subject") or "Meeting via Mail Pilot",
            slot=slots[0],
            attendees=attendees,
            description=f"Scheduled via Mail Pilot.\n\nOriginal request:\n{email['body'][:500]}"
        )
        print(f"[SCHEDULE] Event: {event_result}")

    try:
        summary_resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {os.getenv('GROQ_API_KEY')}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "Summarize this scheduling email in exactly one sentence. "
                            "Mention who wants to meet, when, and with whom if mentioned. "
                            "Be concise and specific. No bullet points."
                        )
                    },
                    {
                        "role": "user",
                        "content": email["body"][:500]
                    }
                ],
                "temperature": 0,
                "max_tokens": 60
            },
            timeout=10
        ).json()
        ai_summary = summary_resp["choices"][0]["message"]["content"].strip()
    except Exception:
        ai_summary = f"Scheduling request from {email['sender']}"

    if event_result and event_result.get("status") == "created":
        html_link = event_result.get("html_link", "")
        log_activity("Meeting scheduled", f"{ai_summary}|{html_link}", "success")
    elif event_result and event_result.get("status") == "duplicate":
        log_activity("Duplicate meeting blocked", ai_summary, "info")
    else:
        log_activity("Schedule request - no slots found", ai_summary, "error")

    reply = build_schedule_reply(slots, event_result, attendees)
    send_reply(service, email, reply)
    print("[SCHEDULE] Reply sent")


def handle_update(service, email):
    print(f"[UPDATE] {email['subject']}")
    try:
        thread_messages = get_thread_messages(service, email["thread_id"])

        thread_text = "\n\n".join([
            f"From: {msg.get('sender', 'Unknown')}\n{msg.get('body', msg.get('snippet', ''))[:300]}"
            for msg in thread_messages[-5:]
        ])

        summary_resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {os.getenv('GROQ_API_KEY')}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "Summarize this email thread in exactly 1-2 sentences. "
                            "Be specific about what was discussed and what the current status is. "
                            "Do not use bullet points. Just plain sentences."
                        )
                    },
                    {
                        "role": "user",
                        "content": thread_text
                    }
                ],
                "temperature": 0,
                "max_tokens": 100
            },
            timeout=10
        ).json()

        ai_summary = summary_resp["choices"][0]["message"]["content"].strip()
        print(f"[UPDATE] AI Summary: {ai_summary}")

        reply = (
            f"Hi,\n\nHere's a summary of this thread:\n\n{ai_summary}\n\n"
            "Let me know if you need more details!"
            + AI_DISCLAIMER
        )
        log_activity("Thread summarized", ai_summary, "success")

    except Exception as e:
        print(f"[UPDATE] Could not fetch thread: {e}")
        log_activity("Thread summarization failed", email['subject'], "error")
        reply = (
            "Hi,\n\nThank you for your message. I'm reviewing the latest updates "
            "from this thread and will get back to you shortly.\n\nBest regards,\nMail Pilot Assistant"
            + AI_DISCLAIMER
        )
    send_reply(service, email, reply)
    print("[UPDATE] Reply sent")


def handle_other(service, email):
    print(f"[OTHER] {email['subject']}")
    try:
        reply_resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {os.getenv('GROQ_API_KEY')}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a professional email assistant called Mail Pilot. "
                            "Reply to the following email politely and helpfully in 2-3 sentences. "
                            "If you cannot help with something specific, say so gracefully and suggest they follow up directly. "
                            "Do not make up information. Be warm but concise."
                        )
                    },
                    {
                        "role": "user",
                        "content": f"Subject: {email['subject']}\n\n{email['body'][:500]}"
                    }
                ],
                "temperature": 0.7,
                "max_tokens": 150
            },
            timeout=10
        ).json()

        ai_reply = reply_resp["choices"][0]["message"]["content"].strip()

    except Exception as e:
        print(f"[OTHER] Groq reply failed: {e}")
        ai_reply = "Thank you for your message! We'll get back to you as soon as possible."

    reply = f"Hi,\n\n{ai_reply}\n\nBest regards,\nMail Pilot Assistant" + AI_DISCLAIMER
    send_reply(service, email, reply)
    log_activity("General reply sent", f"Replied to: {email['subject']}", "info")
    print("[OTHER] Reply sent")


def process_email(service, email):
    print(f"\nFrom: {email['sender']}")
    print(f"Subject: {email['subject']}")

    log_activity("Email received", f"From {email['sender']} — {email['subject']}", "info")

    category = classify_email(email["subject"], email["body"])
    print(f"Category: {category}")

    if category == "SCHEDULE":
        handle_schedule(service, email)
    elif category == "UPDATE":
        handle_update(service, email)
    else:
        handle_other(service, email)

    try:
        mark_as_read(service, email["id"])
    except Exception as e:
        print(f"Could not mark as read: {e}")

    save_processed_id(email["id"])


# ─────────────────────────────────────────────
# POLLING LOOP
# ─────────────────────────────────────────────

def polling_loop(interval_seconds=20):
    service = get_gmail_service()
    print("Mail Pilot started. Polling every 20 seconds...")
    while True:
        try:
            processed_ids = load_processed_ids()
            emails = get_unread_emails(service)
            new_emails = [e for e in emails if e["id"] not in processed_ids]
            if new_emails:
                print(f"\nFound {len(new_emails)} new email(s)")
                for email in new_emails:
                    process_email(service, email)
            else:
                print("No new emails.")
        except Exception as e:
            print(f"Error: {e}")
        time.sleep(interval_seconds)


if __name__ == "__main__":
    polling_loop()